import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';

const pretendard = localFont({
  src: '../fonts/Pretendard_Variable.woff2',
  weight: '100 900',
  style: 'normal',
  display: 'swap',
  variable: '--font-pretendard', // CSS 변수 설정
});

const loosNormal = localFont({
  src: [
    {
      path: '../fonts/LoosNormal_Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/LoosNormal_Medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-loos-normal', // CSS 변수 설정
});

export const metadata: Metadata = {
  title: 'CEOS Vote',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${loosNormal.variable} ${pretendard.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
